import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


class SIEMExporter:
    """
    Export SENTINEL fusion results as Elastic Common Schema (ECS) JSON.
    Compatible with Elastic SIEM, Splunk (via ECS), and IBM QRadar.
    """

    @staticmethod
    def to_ecs(data: dict) -> dict:
        """
        Convert fused CTI data to full ECS-compliant SIEM alert.
        Includes: multi-source provenance, conflict flags, SOAR playbook reference.
        """
        ioc_type = data.get("ioc_type", "unknown")
        severity = data.get("severity", "INFO").upper()

        # Map internal severity to ECS numeric
        SEVERITY_NUM = {"CRITICAL": 1, "HIGH": 2, "MEDIUM": 3, "LOW": 4, "INFO": 5}
        severity_code = SEVERITY_NUM.get(severity, 5)

        # Build indicator block
        indicator = {
            "type": ioc_type,
            "confidence": data.get("confidence", "medium"),
            "marking": {"tlp": "RED"},
        }
        if ioc_type == "ipv4":
            indicator["ip"] = data.get("ip")
        elif ioc_type in ("sha256", "md5", "sha1"):
            indicator["file"] = {"hash": {ioc_type: data.get("hash")}}
        elif ioc_type == "domain":
            indicator["domain"] = data.get("domain") or data.get("ip")
        else:
            indicator["reference"] = data.get("ip") or data.get("hash", "unknown")

        # Build provenance block: source_name → timestamp
        provenance: dict = {}
        feed_results = data.get("feed_results", {})
        for src, res in feed_results.items():
            if isinstance(res, dict) and res.get("status") == "ok":
                provenance[src] = res.get("timestamp", "")

        # Conflict summary
        conflicts = data.get("integrity_conflicts") or []
        conflict_summary = (
            "; ".join(c.get("description", "") for c in conflicts[:3])
            if conflicts else None
        )

        ecs_alert = {
            "@timestamp": datetime.now(timezone.utc).isoformat(),
            "event": {
                "kind": "alert",
                "category": ["threat"],
                "type": ["indicator"],
                "outcome": "success",
                "severity": severity_code,
                "risk_score": data.get("risk_score_numeric", _severity_to_score(severity)),
            },
            "rule": {
                "id": "SENTINEL-MULTIFEED-01",
                "name": "SENTINEL Multi-Source CTI Fusion Alert",
                "description": (
                    "Alert generated by SENTINEL Threat Fusion Engine after correlating "
                    "VirusTotal, AlienVault OTX, MalwareBazaar, URLhaus, and TAXII/STIX feeds."
                ),
                "category": "threat-intelligence",
                "version": "2.0",
            },
            "threat": {
                "indicator": indicator,
                "feed": {
                    "name": "SENTINEL Multi-Source Fusion Engine",
                    "dashboard_id": "sentinel-cti-dashboard",
                },
                "framework": "MITRE ATT&CK",
                "tactic": data.get("mitre_tactics", []),
                "technique": data.get("mitre_techniques", []),
            },
            "vulnerability": {
                "severity": severity.lower(),
            },
            "sentinel": {
                "integrity_conflict": data.get("integrity_conflict", False),
                "conflict_summary": conflict_summary,
                "active_sources": data.get("active_sources", []),
                "consensus_severity": severity,
                "aggregate_confidence": data.get("confidence_score", 0.5),
                "visual_artefacts_detected": data.get("visual_found", False),
                "reasoning_chain": data.get("reasoning", "")[:2000],  # truncate for SIEM
                "provenance": provenance,
            },
            "affected_assets": data.get("affected_assets", ["UNKNOWN"]),
            "recommended_actions": data.get("recommended_actions", [
                "Monitor target in threat intelligence feeds",
                "Review network traffic to/from this indicator",
                "Consult SOAR playbook for detailed response steps",
            ]),
            "tags": ["sentinel", "cti", "multi-source", "automated"],
        }

        # Add integrity conflict warning to tags if applicable
        if data.get("integrity_conflict"):
            ecs_alert["tags"].append("INTEGRITY-CONFLICT")
            ecs_alert["tags"].append("MANUAL-REVIEW-REQUIRED")

        return ecs_alert

    @staticmethod
    def save_json(alert: dict, filename: str = "siem_alert_export.json") -> str:
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(alert, f, indent=4, ensure_ascii=False)
        return filename

    @staticmethod
    def generate_soar_playbook(
        target: str,
        risk_score: str,
        integrity_conflict: bool,
        active_sources: List[str],
        ttps: Optional[List[dict]] = None,
        conflict_details: Optional[List[dict]] = None,
    ) -> str:
        """
        Generate a standalone SOAR playbook Markdown file.
        This is the dedicated D3 deliverable — separate from the LIA PDF.
        """
        ttps = ttps or []
        conflict_details = conflict_details or []
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        RESPONSE_LEVEL = {
            "CRITICAL": "🔴 **FULL INCIDENT RESPONSE** — Isolasi aset, aktivasi tim IR",
            "HIGH":     "🟠 **ACTIVE CONTAINMENT** — Blokir IoC, notifikasi eksekutif",
            "MEDIUM":   "🟡 **ENHANCED MONITORING** — Notifikasi Tim SOC, analisis lanjutan",
            "LOW":      "🟢 **STANDARD MONITORING** — Pantau traffic, log untuk tren",
            "INFO":     "🔵 **INFORMATIONAL** — Catat untuk referensi, tidak perlu aksi langsung",
        }
        response = RESPONSE_LEVEL.get(risk_score.upper(), "🔵 **INFORMATIONAL**")

        lines = [
            f"# 🛡️ SOAR Playbook — SENTINEL CTI Engine",
            f"**Target:** `{target}`  ",
            f"**Risk Score:** {risk_score}  ",
            f"**Generated:** {ts}  ",
            f"**Active Sources:** {', '.join(active_sources or ['N/A'])}  ",
            f"**Integrity Conflict:** {'⚠️ YA — Lihat Seksi Konflik' if integrity_conflict else '✅ Tidak'}",
            "",
            "---",
            "",
            "## 1. Trigger Condition",
            f"SENTINEL Fusion Engine mendeteksi `{target}` dengan risk score **{risk_score}** "
            f"berdasarkan korelasi {len(active_sources or [])} sumber CTI aktif.",
            "",
        ]

        if integrity_conflict and conflict_details:
            lines += [
                "## ⚠️ 2. PERINGATAN: Konflik Integritas Terdeteksi",
                "**WAJIB: Validasi manual sebelum mengeksekusi langkah containment apa pun.**",
                "",
                "Detail konflik:",
            ]
            for i, c in enumerate(conflict_details, 1):
                lines.append(
                    f"- **Konflik #{i}:** {c.get('source_a', '?')} [{c.get('severity_a', '?')}] "
                    f"vs {c.get('source_b', '?')} [{c.get('severity_b', '?')}] — {c.get('description', '')}"
                )
            lines += ["", "---", ""]

        lines += [
            f"## {'3' if integrity_conflict else '2'}. Scope & Affected Assets",
            "- Identifikasi semua sistem yang telah berkomunikasi dengan target IoC",
            "- Periksa log firewall, DNS query, dan proxy untuk koneksi ke target",
            "- Tandai endpoint yang berpotensi terekspos",
            "",
            f"## {'4' if integrity_conflict else '3'}. Langkah Investigasi",
            f"1. **[VirusTotal]** Periksa laporan lengkap: `https://virustotal.com/`",
            f"2. **[Abuse.ch]** Periksa URLhaus dan MalwareBazaar untuk konteks tambahan",
            f"3. **[Internal]** Cari IoC `{target}` di log SIEM 30 hari terakhir",
            f"4. **[Endpoint]** Pindai endpoint terkait dengan EDR/antivirus terbaru",
            f"5. **[Network]** Analisis pcap jika tersedia untuk pola komunikasi C2",
        ]


        if ttps:
            lines += ["", "### TTPs Teridentifikasi:"]
            for t in ttps[:5]:
                lines.append(f"- `{t.get('technique_id', 'T????')}` {t.get('technique_name', '')} "
                             f"({t.get('tactic', '')})")

        lines += [
            "",
            f"## {'5' if integrity_conflict else '4'}. Tindakan Containment",
        ]

        if risk_score in ("CRITICAL", "HIGH"):
            lines += [
                f"{response}",
                "- ⛔ Blokir IoC di firewall, DNS sinkhole, dan proxy",
                "- 🔒 Isolasi endpoint yang terinfeksi dari jaringan",
                "- 📞 Notifikasi tim manajemen insiden dan stakeholder kritis",
                "- 📋 Buka tiket insiden dengan severity sesuai risk score",
            ]
        elif risk_score == "MEDIUM":
            lines += [
                f"{response}",
                "- 🔍 Tingkatkan level monitoring untuk IoC ini selama 72 jam",
                "- 📬 Kirim notifikasi kepada Tim SOC Level 2",
                "- 📋 Buat watchlist rule di SIEM untuk trigger alert jika muncul lagi",
            ]
        else:
            lines += [
                f"{response}",
                "- 📊 Tambahkan IoC ke threat intel watchlist",
                "- 🔍 Monitor log harian untuk kemunculan kembali",
            ]

        lines += [
            "",
            f"## {'6' if integrity_conflict else '5'}. Eradikasi",
            "- Hapus file/proses berbahaya yang teridentifikasi dari endpoint",
            "- Reset kredensial yang berpotensi terekspos",
            "- Patch vulnerability yang dieksploitasi (jika CVE teridentifikasi)",
            "",
            f"## {'7' if integrity_conflict else '6'}. Post-Incident",
            "- Dokumentasikan timeline insiden dan tindakan yang diambil",
            "- Update signature dan rule SIEM berdasarkan temuan",
            "- Laksanakan post-mortem dalam 48 jam setelah resolusi",
            "- Share IoC ke platform CTI internal untuk enrichment future alerts",
            "",
            f"## {'8' if integrity_conflict else '7'}. MITRE ATT&CK Reference",
        ]
        if ttps:
            for t in ttps:
                lines.append(f"- [{t.get('technique_id', '')}] {t.get('technique_name', '')} — {t.get('tactic', '')}")
        else:
            lines += [
                "- TTPs tidak teridentifikasi secara eksplisit dari data feed",
                "- Konsultasikan laporan LIA untuk konteks adversary",
            ]

        lines += [
            "",
            f"## {'9' if integrity_conflict else '8'}. Kriteria Eskalasi",
            "- Eskalasi ke CISO jika risk_score = CRITICAL atau HIGH",
            "- Eskalasi ke Tim IR jika IoC ditemukan aktif di jaringan internal",
            "- Eskalasi jika integrity_conflict tidak dapat diselesaikan dalam 4 jam",
            "",
            "---",
            "*Playbook ini dihasilkan otomatis oleh SENTINEL CTI Platform. "
            "Validasi oleh SOC Analyst wajib sebelum eksekusi tindakan kritis.*",
        ]

        return "\n".join(lines)


def _severity_to_score(severity: str) -> float:
    """Convert severity string to numeric risk score."""
    return {"CRITICAL": 95.0, "HIGH": 75.0, "MEDIUM": 50.0, "LOW": 25.0, "INFO": 5.0}.get(severity, 5.0)
